### ISSUE TITLE
Reset via Konsole

### ISSUE THREAD

**Issue by MisterGamingTV** [FixlTV/discord-for-school#12]
Man könnte einen Command für die Konsole einbauen, über den man alle oder nur bestimmte Einstellungen ändern kann.

**Comment by FixlTV** [comment]
Also, ich habs jetzt erstmal so gemacht, dass der Bot nach einem Update auch noch funktioniert, wenn Einstellungen geändert werden müssen, dann wird der Assistant nochmal gestartet (btw auch relevant für #6).  
Ob ich jetzt Einstellungen variabel mach, muss ich schauen, ich mein Dateien bearbeiten sollte man hinbekommen, wenn man es schafft, den Bot/Git zu installieren
