### ISSUE TITLE
Setup Bug

### ISSUE THREAD

**Issue by olebohmbach** [FixlTV/discord-for-school#14]
![image](https://user-images.githubusercontent.com/77053238/153709755-e4a301cf-976c-411b-879e-b6db65fdf64b.png)
Wenn man "n" angibt, nimmt der glaub ich trotzdem "y"

**Comment by FixlTV** [comment]
Eigentlich nicht, glaub es liegt an was anderen, schaus mir mal an. Glaube, #15 resultiert aus diesem Fehler

**Comment by FixlTV** [comment]
Sollte jetzt gehen, wenn du eine `vertretungsplan.js` und/oder einen `vertretungsplan` Ordner hast, einfach löschen und in der `config.json` "vtp" auf false setzen
