### ISSUE TITLE
Bot crasht wenn man auf Settings -> Ignorierte Fächer geht

### ISSUE THREAD

**Issue by olebohmbach** [FixlTV/discord-for-school#15]
https://cdn.ole-is-live.de/Discord_PJHWUXCXnf.mp4 
![image](https://user-images.githubusercontent.com/77053238/153709881-cd6e898d-b86c-4473-8fbd-722ea4fa1852.png)

**Comment by FixlTV** [comment]
Kann ich nicht reproduzieren, kannst du mal bitte deine `data/subjects.json` schicken bitte?

**Comment by FixlTV** [comment]
> https://cdn.ole-is-live.de/Discord_PJHWUXCXnf.mp4 ![image](https://user-images.githubusercontent.com/77053238/153709881-cd6e898d-b86c-4473-8fbd-722ea4fa1852.png)

~~Btw ist das Bild alles vom Error?~~
Seh ich grad, aber basically steht da nicht, warum er gecrasht ist, oder?
