### ISSUE TITLE
[Vorschlag] Gerade / ungerade Woche (A/B Woche)

### ISSUE THREAD

**Issue by Zoey2936** [FixlTV/discord-for-school#5]
Da bei uns in der Schule der Stundenplan oder zumindest einzelne Fächer sich in geraden / ungerade Wochen unterscheiden, wäre es schön, wenn der Stundenplan die aktuellen Kalenderwochen Nummer des Tages mit anzeigen würde

Aber sehr schönes projekt!

**Comment by DavidCraftDev** [comment]
Oh das wird ein Spaß für @FixlTV das zu implementieren xD
Da es im JS keine Implementierte Funktion dafür gibt

**Comment by Zoey2936** [comment]
Bisher nutzte ich immer die Website: https://aktuelle-kalenderwoche.org xD

**Comment by DavidCraftDev** [comment]
Man kann ja einfach die Webseite verlinken xD

**Comment by FixlTV** [comment]
Ich probiers mal...  
Könnte aber noch bissl dauern, bis das kommt

**Comment by FixlTV** [comment]
Anleitung soon

**Comment by DavidCraftDev** [comment]
soon™️

**Comment by FixlTV** [comment]
Anleitung fertig, das Teil sollte eigentlich auch funktionieren, habs jetzt aber nicht groß getestet. Wie es ist wenn man beispielsweise eine Stunde Physik jede Woche hat und danach Physik oder Chemie, abhängig eben von der KW, weiß ich nicht ganz, theoretisch könnte/sollte es aber gehen

**Comment by Zoey2936** [comment]
> Anleitung fertig, das Teil sollte eigentlich auch funktionieren, habs jetzt aber nicht groß getestet. Wie es ist wenn man beispielsweise eine Stunde Physik jede Woche hat und danach Physik oder Chemie, abhängig eben von der KW, weiß ich nicht ganz, theoretisch könnte/sollte es aber gehen

wo findet man die anleitung? bin blind

**Comment by FixlTV** [comment]
https://github.com/FixlTV/discord-for-school/wiki/Informationen-f%C3%BCr-Developer#stundenplan
