### ISSUE TITLE
Update Anleitung

### ISSUE THREAD

**Issue by Zoey2936** [FixlTV/discord-for-school#6]
Wie wäre es mit einer Update-Anleitung oder einem Update Script?

**Comment by Zoey2936** [comment]
Unter Linux (also getestet unter Debian 11) geht das (wenn man wget und unzip installiert hat):

```sh
wget https://github.com/FixlTV/discord-for-school/archive/refs/heads/main.zip
unzip -o main.zip
rm main.zip
```

**Comment by FixlTV** [comment]
> Wie wäre es mit einer Update-Anleitung oder einem Update Script?

Meinst du, dass der Bot sich selbst updatet?

**Comment by Zoey2936** [comment]
> > Wie wäre es mit einer Update-Anleitung oder einem Update Script?
> 
> Meinst du, dass der Bot sich selbst updatet?

das wär am besten

**Comment by FixlTV** [comment]
oke, ich kann mal schauen, ist halt doof wegen Betriebssystemen und so

**Comment by Zoey2936** [comment]
> oke, ich kann mal schauen, ist halt doof wegen Betriebssystemen und so

Aber eine allgemeine Update-Anleitung wäre zumindest auch sehr gut.

**Comment by FixlTV** [comment]
Ich denk, ich werd die Update Funktion mit Git machen, dass der dann einfach nen pull macht, ist einfach und betriebssystemübergreifend

**Comment by Zoey2936** [comment]
Packst du auch einen git Installer hinzu?

**Comment by FixlTV** [comment]
Kann ich in die Anleitung packen

**Comment by FixlTV** [comment]
Passt das so als [Anleitung](../wiki/Informationen-für-Developer#update)? 
Bezüglich der Update Funktion, jetzt wird schonmal bei nem Pull überprüft, ob das System noch einsatzbereit ist und, wenn neue Daten benötigt werden, wird jetzt aufgefordert, die einzugeben.

**Comment by Zoey2936** [comment]
> Passt das so als [Anleitung](../wiki/Informationen-f%C3%BCr-Developer#update)? 

Ja

**Comment by FixlTV** [comment]
Aso, das gibts jetzt btw so teilweise.  
Ka, ob ich das hier schon gesagt hab aber Hauptmenü > Einstellungen > Entwickler-Einstellungen > Update.  
Um die Entwickler Einstellungen zu sehen, muss man btw in der Config als Mod gespeichert sein. Und das Unicode Symbol, was den Update Knopf im 2. Fenster darstellt, gibts ned auf iOS

**Comment by DavidCraftDev** [comment]
Kein iOS Support? Schande 🌚

**Comment by Zoey2936** [comment]
> Aso, das gibts jetzt btw so teilweise. Ka, ob ich das hier schon gesagt hab aber Hauptmenü > Einstellungen > Entwickler-Einstellungen > Update. Um die Entwickler Einstellungen zu sehen, muss man btw in der Config als Mod gespeichert sein. Und das Unicode Symbol, was den Update Knopf im 2. Fenster darstellt, gibts ned auf iOS

Bitte nochmal, ich habs nicht verstanden. Danke xD

**Comment by FixlTV** [comment]
https://discord.com/channels/775001585541185546/935974565430042685/941759565148618782 Da
